name 'systemd_timesyncd'
maintainer 'Matt Ray'
maintainer_email 'matt@chef.io'
license 'Apache-2.0'
description 'Installs/Configures systemd-timesyncd'
version '0.2.0'
chef_version '>= 16.0'

issues_url 'https://github.com/mattray/systemd_timesyncd-cookbook/issues'
source_url 'https://github.com/mattray/systemd_timesyncd-cookbook'
